apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: node-js-
  labels:
    workflows.argoproj.io/archive-strategy: "false"
  annotations:
    workflows.argoproj.io/description: |
      This is a simple hello world example.
      You can also run it in Python: https://couler-proj.github.io/couler/examples/#hello-world
spec:
  entrypoint: node-js
  templates:
  - name: node-js
    container:
      image: node:alpine
      command: [cowsay]
      args: ["hello world"]