apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: node-js-
spec:
  entrypoint: node-js
  templates:
  - name: node-js
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["hello world"]